### ISSUE TITLE
We need a basic website

### ISSUE THREAD

**Issue by kevbite** [dotnetYork/dotnetYork.github.io#1]
We're a local user group which is just starting up, and we'd love a website!

The website just needs to be a basic static website for the time being with some information about our group.

We have a logo 
![](https://pbs.twimg.com/profile_images/905333691253174272/gV1AUwzC_400x400.jpg)
This  uses [DS Dots](http://ttfonts.net/font/13691_DSDots.htm) font.

We have a twitter feed: https://twitter.com/dotnetyork
We have a facebook page: https://www.facebook.com/dotnetyork/
We have a meetup page https://www.meetup.com/dotnetyork

We would love to see something creative and don't mind what languages and tools you use!

**Comment by Frewacom** [comment]
I could work on this, but I would need more details about what I need to do.

**Comment by kevbite** [comment]
Hello @Frewacom, thanks for wanting to help out!

The site can be as simple or as complex as you want to make it, we're happy with a totally static or a statically generate website with something like [Jekyll](https://jekyllrb.com/)

We'd ideally want the blurb about our group:
> dotnetYork is a .NET user group focusing on any .NET related technology. we're based in York, northeast England.
> dotnetYork is a new .NET user group looking to focus on .NET and anything related to .NET ecosystem. We encourage developers of any skill level to come join in on our events to either learn or share.

And some link backs to our meetup, twitter and facebook page.

It would be also nice to have the next event on the main page, this could either be manually updated or if possible could pull from the Meetup API.

Simple, however, might be the key here.

Thanks

Kev

**Comment by kevbite** [comment]
Also if it is easier we could break it down into small Issues that we could discuss in isolation. 👍

**Comment by Yogendra0Sharma** [comment]
I would like to work on it. Please assign it to me.
is it require to use .Net technology for this website or we can develop it in any tech stack?

**Comment by kevbite** [comment]
We're open to any type of technology stack.

**Comment by kevbite** [comment]
@Frewacom do you want to take this one? You were first to the issue so get the choice.

We could however, split it down so both of you could work on it?

**Comment by Yogendra0Sharma** [comment]
@Frewacom : sure please assign it to me. 

I'll create a website with home, about, contact, events pages.
homepage showing upcoming events and basic information.
is it fine ?

**Comment by pet3r-pan** [comment]
I just took a shot a this during my lunch break

**Comment by kevbite** [comment]
Is it possible to assign people who have not got write access to the repo?

**Comment by Frewacom** [comment]
@Yogendra0Sharma can take it. He seems to have a pretty clear image of what he wants to do. Good luck!

EDIT: If you need help with anything else, just tag me.

**Comment by peterdennispan** [comment]
I tried :( hope u like https://a.pomfe.co/snmpeqd.html

**Comment by kevbite** [comment]
Thanks @Frewacom! @Yogendra0Sharma feel free to have a stab at this 👍

**Comment by peterdennispan** [comment]
I tried

`<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dotnet Group</title>

    <style>

@media (min-width: 600px) {
  body {
    padding-top: 100px;
  }
}

@media (min-width: 300px) {
  body {
    padding-top: 50px;
  }
}

    body {
      background-color: blue;
      background-repeat: repeat;
      color: white;
      height: 100vh;
      text-align: center;
    }

    a {
      color: white;
    }

    img {
      max-width: 600px;
    }

    #yeah {
      max-width: 300px;
    }

    a:hover {
      color: black;
    }

    a:focus {
      color: pink;
    }

    </style>

  </head>

  <body>
    <img src="http://www5.flamingtext.com/Tools/download/coollogo_com.gif?url=https://de17-engine.flamingtext.com/netfu/tmp28005/coollogo_com-31417125.gif&_loc=image" />
          <p class="">
            Cool hackers group organised by<a href="https://twitter.com/kev_bite">@kev_bite</a> and supported by<a href="https://twitter.com/YorkDevelopers">@YorkDevelopers</a>
          </p>
          <h1>
            <a href="https://twitter.com/YorkDevelopers">Twitter</a>
            <a href="https://www.facebook.com/dotnetYork/">Facebook</a>
            <a href="https://www.meetup.com/dotnetyork">Meetup</a>
          </h1>
          <img id="yeah" src="http://i2.kym-cdn.com/photos/images/masonry/000/328/411/082" />

  </body>

</html>
`

**Comment by kevbite** [comment]
@peterdennispan I seem to get a _403 Forbidden_

![image](https://user-images.githubusercontent.com/5544715/31120104-329739e0-a82b-11e7-96ae-f6b8ab32b210.png)

**Comment by pet3r-pan** [comment]
Put this into html https://pastebin.com/QKyHhc1d

**Comment by kevbite** [comment]
@Yogendra0Sharma I sent you a colloborator invite.

**Comment by pet3r-pan** [comment]
I personally believe good design is overrated and I am a designer. Nostalgia UX > good design

**Comment by kevbite** [comment]
@Yogendra0Sharma hows it going? do you need anything from me?

**Comment by kevbite** [comment]
@peterdennispan little bit of advice for contributing is to start a discussion before just running in and creating someone, it helps on both sides! 👍

**Comment by Yogendra0Sharma** [comment]
@kevbite : Working on it. Probably will finish basic design today end of the day.

**Comment by kevbite** [comment]
@Yogendra0Sharma nice one, well give me a shout if you need anything from me!

**Comment by kevbite** [comment]
Any outlook on this @Yogendra0Sharma?
